on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        if: false
        with:
          node-version: '18.19.1'

      - name: Install Dependencies
        run: npm ci
        if: false

      - name: Run Tests
        run: npm run test
        if: false
